# Generated by Django 5.0.6 on 2024-06-09 18:51

import bond_service.base.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('isin', models.CharField(db_index=True, help_text='The ISIN (International Securities Identification Number) of the bond.', max_length=12, unique=True, validators=[bond_service.base.validators.validator_isin])),
                ('value', models.DecimalField(decimal_places=2, help_text='The value of the bond. Must be a positive number.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='The interest rate of the bond in percent (0-100%).', max_digits=5, validators=[bond_service.base.validators.validator_interest_rate])),
                ('purchase_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('interest_payment_frequency', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
